[[redirects]]
  from = "/api/*"
  to = "https://shawnx-6d26c8cc075a.herokuapp.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
